import { readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const rootDir = resolve(__dirname, '..')
const srcDir = resolve(rootDir, 'src')
const outputFile = resolve(srcDir, 'icons.js')
const sourceDirs = ['components', 'views']

const iconPattern = /icon="([a-z0-9-]+):([a-z0-9-]+)"/gi

function sortObjectKeys(value) {
  return Object.fromEntries(
    Object.entries(value).sort(([left], [right]) => left.localeCompare(right)),
  )
}

async function collectVueFiles(dirPath) {
  const entries = await readdir(dirPath, { withFileTypes: true })
  const files = []

  for (const entry of entries) {
    const fullPath = resolve(dirPath, entry.name)

    if (entry.isDirectory()) {
      files.push(...await collectVueFiles(fullPath))
      continue
    }

    if (entry.isFile() && entry.name.endsWith('.vue')) {
      files.push(fullPath)
    }
  }

  return files
}

async function getSourceFiles() {
  const files = []

  for (const dir of sourceDirs) {
    files.push(...await collectVueFiles(resolve(srcDir, dir)))
  }

  return files.sort((left, right) => left.localeCompare(right))
}

function buildCollectionCode(prefix, collection) {
  const lines = [
    'addCollection({',
    `  prefix: ${JSON.stringify(prefix)},`,
  ]

  if (typeof collection.width === 'number') {
    lines.push(`  width: ${collection.width},`)
  }

  if (typeof collection.height === 'number') {
    lines.push(`  height: ${collection.height},`)
  }

  lines.push('  icons: {')

  for (const [name, iconData] of Object.entries(collection.icons)) {
    lines.push(`    ${JSON.stringify(name)}: ${JSON.stringify(iconData)},`)
  }

  lines.push('  },', '})')
  return lines.join('\n')
}

async function loadUsedIcons() {
  const usedIcons = new Map()
  const sourceFiles = await getSourceFiles()

  for (const filePath of sourceFiles) {
    const content = await readFile(filePath, 'utf8')

    for (const match of content.matchAll(iconPattern)) {
      const [, prefix, iconName] = match
      if (!usedIcons.has(prefix)) {
        usedIcons.set(prefix, new Set())
      }
      usedIcons.get(prefix).add(iconName)
    }
  }

  return usedIcons
}

async function loadCollection(prefix) {
  try {
    const packageJsonUrl = await import.meta.resolve(`@iconify-json/${prefix}/icons.json`)
    const filePath = fileURLToPath(packageJsonUrl)
    const content = await readFile(filePath, 'utf8')
    return JSON.parse(content)
  } catch (error) {
    throw new Error(`缺少图标集 @iconify-json/${prefix}，请先安装对应依赖。`)
  }
}

async function generate() {
  const usedIcons = await loadUsedIcons()
  const collections = []

  for (const [prefix, iconNames] of [...usedIcons.entries()].sort(([left], [right]) => left.localeCompare(right))) {
    const source = await loadCollection(prefix)
    const icons = {}

    for (const iconName of [...iconNames].sort((left, right) => left.localeCompare(right))) {
      const iconData = source.icons?.[iconName]
      if (!iconData) {
        throw new Error(`图标 ${prefix}:${iconName} 不存在于 @iconify-json/${prefix}。`)
      }
      icons[iconName] = iconData
    }

    collections.push(buildCollectionCode(prefix, {
      width: source.width,
      height: source.height,
      icons: sortObjectKeys(icons),
    }))
  }

  const output = [
    '// Auto-generated by scripts/generate-icons.mjs. Do not edit manually.',
    "import { addCollection } from '@iconify/vue/offline'",
    '',
    collections.join('\n\n'),
    '',
  ].join('\n')

  await writeFile(outputFile, output, 'utf8')
  console.log(`Generated ${outputFile}`)
}

generate().catch((error) => {
  console.error(error.message)
  process.exitCode = 1
})
